name: Build

on: workflow_dispatch

permissions: write-all

jobs:
  Windows:
    runs-on: windows-2019
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirement.txt

      - name: Dependencies
        shell: pwsh
        run: |
          python -m pip install -U -r requirements.txt

      - name: Build
        run: |
          python -m lndl_nuitka . -y -- --disable-console


      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: LoCyanPyLauncher-Windows
          path: |
            main.exe

  Linux:
    runs-on: ubuntu-latest
    steps:

      - name: Install Tools
        run: |
          sudo apt-get install libfuse2

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirement.txt

      - name: Dependencies
        shell: pwsh
        run: |
          python -m pip install -U -r requirements.txt

      - name: Build
        run: |
          python -m lndl_nuitka . -y -- --disable-console

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: LoCyanPyLauncher-Linux
          path: |
            main.bin
