name: Build and Release

on: workflow_dispatch

permissions: write-all

jobs:
  Windows:
    runs-on: windows-2019
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirement.txt

      - name: Dependencies
        shell: pwsh
        run: |
          python -m pip install -U -r requirements.txt

      - name: Build
        run: |
          python -m lndl_nuitka . -y -- --disable-console


      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MCSL2-Windows-x64
          path: |
            build/MCSL2.dist/**/*

  Linux:
    runs-on: ubuntu-20.04
    steps:

      - name: Install Tools
        run: |
          sudo apt-get install libfuse2

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirement.txt

      - name: Dependencies
        shell: pwsh
        run: |
          python -m pip install -U -r requirements.txt

      - name: Build
        run: |
          python -m lndl_nuitka . -y -- --disable-console

#  Release:
#    runs-on: ubuntu-20.04
#
#    needs:
#      - Windows
#      - Linux
#
#    steps:
#
#      - uses: szenius/set-timezone@v1.0
#        with:
#          timezoneLinux: 'Asia/Shanghai'
#
#      - name: Install Tools
#        run: sudo apt install p7zip-full
#
#      - name: Download Artifacts
#        uses: actions/download-artifact@v3
#
#      - name: Checkout repository
#        uses: actions/checkout@v4
#        with:
#          path: repo
#
#      - name: Set Environment Variable
#        run: |
#          cd repo
#          mcsl2_version=$(python -c "from MCSL2Lib import MCSL2VERSION; print(MCSL2VERSION)")
#          echo "MCSL2_VERSION=$mcsl2_version" >> $GITHUB_ENV
#          cd ..
#
#      - name: Compress
#        run: |
#          7z a -tzip "MCSL2-${{ env.MCSL2_VERSION }}-Windows-x64.zip" "./MCSL2-Windows-x64/*"
#          7z a -tzip "MCSL2-${{ env.MCSL2_VERSION }}-Linux-x64.zip" "./MCSL2-Linux-x64/*"
#          mkdir Update
#          cd Update
#          mkdir Linux-x64 Windows-x64
#          cd Linux-x64
#          mkdir MCSL2Lib
#          cd ..
#          cd Windows-x64
#          mkdir MCSL2Lib
#          cd ..
#          cp -r ../MCSL2-Linux-x64/MCSL2.bin Linux-x64/
#          cp -r ../MCSL2-Windows-x64/MCSL2.exe Windows-x64/
#          cp -r ../MCSL2-Linux-x64/MCSL2Lib/verification.so Linux-x64/MCSL2Lib/
#          cp -r ../MCSL2-Windows-x64/MCSL2Lib/verification.pyd Windows-x64/MCSL2Lib/
#          cd ..
#          7z a -tzip "Update-${{ env.MCSL2_VERSION }}.zip" "./Update/*"
#
#      - name: Release
#        uses: softprops/action-gh-release@v1
#        with:
#          body_path: ./repo/ChangeLog.md
#          prerelease: false
#          draft: false
#          tag_name: v${{ env.MCSL2_VERSION }}
#          files: |
#            *.zip
#
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}